# Generated by Django 3.2.8 on 2021-11-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('isAuthenticated', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
    ]
