# Generated by Django 3.2.8 on 2021-12-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='performer',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='prices',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='rules',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(default='', max_length=50),
        ),
    ]
