# Generated by Django 3.2.8 on 2021-12-19 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_date_purchase_dateutc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='useremail',
            new_name='user',
        ),
    ]
