# Generated by Django 3.2.8 on 2021-12-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_discountcode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='seatingPlan',
            field=models.TextField(null=True),
        ),
    ]
