# Generated by Django 3.2.8 on 2021-12-19 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_event_seatingplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('listID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
                ('user', models.ManyToManyField(to='api.User')),
            ],
        ),
    ]
